sudo: required
language: go
services:
- docker
go:
## Convert to 1.11.x once it is released
- go1.11rc1
env:
  global:
  - GO111MODULE=on
script:
- go build ./cmd/pack
- go test -parallel 1 -v ./acceptance
